aanpassing eOverdracht Bolt: task specifieke notificatie
nuts-foundation/bolts pull request #16
Opened 2021-12-20 10:55 UTC by woutslakhorst

Deze wijziging bevat de aanpassing van de notificatie. Deze bevat nu een identifier. De opvragende partij hoeft daarna geen Task search meer te doen, maar een specifieke GET op de Task resource.

2021-12-20 13:02 UTC, stevenvegt commented on eoverdracht/leveranciersspecificatie.md
> +Wanneer er een task wordt toegevoegd zal het bronsysteem een notificatie \(lege POST volgens FHIR documentatie\) sturen naar het eerder geregistreerde endpoint van het doelsysteem. Dit is een signaal
>Dit betekent dat de task resource geen persoonsgegevens bevat en dat eventuele referenties naar persoonsgegevens natuurlijk een geautoriseerde gebruiker vereisen.

Dit betekent dat de task resource geen persoonsgegevens (of referenties waarmee een persoon uniek geidentificeerd kan worden) mag bevatten.

2021-12-20 13:06 UTC, stevenvegt commented on eoverdracht/leveranciersspecificatie.md
> +Naast het eerder genoemde voordeel van herbruikbaarheid is een ander voordeel van het gebruik van autorisaties dat de patiënt dit ook inzichtelijk zou kunnen krijgen in een PGO. De patiënt zou op bas
>Naast het eerder genoemde voordeel van herbruikbaarheid is een ander voordeel van het gebruik van autorisaties dat de patiënt dit ook inzichtelijk zou kunnen krijgen in een PGO. De patiënt zou op basis van de autorisaties een overzicht kunnen krijgen van wie zijn of haar gegevens kan inzien, en waarom.

Een ander voordeel van autorisaties is dat de ook de patient een overzicht in het PGO kan krijgen wie welke gegevens waarom kan inzien.

2021-12-23 13:13 UTC, Timendus reviewed
Paar kleine dingetjes. Lekker bezig Wout :)

2021-12-23 13:13 UTC, Timendus commented on eoverdracht/leveranciersspecificatie.md
> +De resource server van de ontvangende partij moet controleren dat er voor het notificatie endpoint een `POST` request wordt gedaan zonder body. Het gaat hierbij om relatief pad t.o.v. wat er geregist
```suggestion
De resource server van de ontvangende partij moet controleren dat er voor het notificatie endpoint een `POST` request wordt gedaan zonder body. Het gaat hierbij om een relatief pad t.o.v. wat er geregistreerd staat onder het `notification` veld in de `eOverdracht-receiver` service. Achter dit pad mag alleen nog een resource identifier staan.
```

2021-12-23 13:13 UTC, Timendus commented on eoverdracht/leveranciersspecificatie.md
> +Omdat het hierbij gaat om de toegang van een enkele resource, is er een [Nuts Authorization Credential](https://nuts-foundation.gitbook.io/drafts/rfc/rfc014-authorization-credential) nodig. Het crede
```suggestion
Omdat het hierbij gaat om de toegang tot een enkele resource, is er een [Nuts Authorization Credential](https://nuts-foundation.gitbook.io/drafts/rfc/rfc014-authorization-credential) nodig. Het credential moet voldoen aan de volgende eisen:
```

2022-01-13 07:48 UTC, MichielBruins-gerimedica commented on eoverdracht/leveranciersspecificatie.md
Het doelsysteem valideert of of de POST leeg is en of er een Task ID aan het base endpoint is verstuurd. Zo niet dan wordt een HTTP error in de 400 range teruggegeven.

2022-01-17 08:07 UTC, woutslakhorst commented
@MichielBruins-gerimedica @Timendus wat regels toegevoegd over HTTP status codes voor de Task notificatie.

2022-01-17 10:36 UTC, dmeijboom approved these changes
LGTM, moeten we nog expliciet melden dat `id` de FHIR identifier van den Task resource moet zijn? Of is dat duidelijk genoeg zo?

2022-01-18 07:53 UTC, woutslakhorst commented
> LGTM, moeten we nog expliciet melden dat `id` de FHIR identifier van den Task resource moet zijn? Of is dat duidelijk genoeg zo?

Dat is idd niet expliciet genoemd, maar is wel volgens de FHIR gedachte...

2022-01-18 10:45 UTC, reinkrul requested changes

2022-01-18 10:45 UTC, reinkrul commented on eoverdracht/leveranciersspecificatie.md
> +Dit laatste endpoint dient het `[base]` path te zijn waarop notificaties ontvangen kunnen worden middels de `Task` resource. De volgende paragraaf beschrijft het notificatie mechanisme. Het betreft d
> Het path dient zonder `/` geregistreerd te worden.

Wordt hiermee bedoelt met een postfix `/`, dus m.a.w. niet eindigend op `/`? Dat is niet helemaal duidelijk.

2022-01-20 06:59 UTC, reinkrul approved these changes

2022-01-20 12:41 UTC, merged